#main.yml 
#this is using biolinux, so apt-get will be the package manager 
--- 
- name: download bsmap 
  get_url: url=http://lilab.research.bcm.edu/dldcc-web/lilab/yxi/bsmap/bsmap-2.90.tgz dest=/home/{{ ansible_user_id }}
  
- name: unpack bsmap 
  unarchive: src=/home/{{ ansible_user_id }}/bsmap-2.90.tgz dest=/home/{{ ansible_user_id}} copy=no

- name: install bsmap 
  command: creates=/usr/bsmap chdir=/home/{{ ansible_user_id }}/bsmap-2.90 make install 
