--- 
sudo: required 

services: 
  - docker

env: 
  - distribution: ubuntu
    version: trusty

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/home:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -i /home/tests/inventory -v /home/tests/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/nginx_role/travis/test.yml'
  - >
     ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo
     | grep -q 'failed=0'
     && (echo 'task failure test: pass' && exit 0)
     || (echo 'task failure test: fail' && exit 1)
         
  - 'sudo docker rm -f "$(cat ${container_id})"'
