--- 
sudo: required 

language: python

python: 
  - "2.7"

env: 
  - distribution: ubuntu
    version: trusty

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup --volume="${PWD}":/home ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_CONFIG=/home/tests/ansible.cfg' 
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -vvv -i inventory -v test.yml --syntax-check'

  - >
     'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -vvv -i /tests/inventory /tests/test.yml'
     | grep -q 'failed=0'
     && (echo 'task failure test: pass' && exit 0)
     || (echo 'task failure test: fail' && exit 1)
         
  - 'sudo docker rm -f "$(cat ${container_id})"'
