FROM ubuntu:trusty

RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y software-properties-common && rm -rf /var/lib/apt/lists/*

RUN apt-add-repository -y ppa:ansible/ansible && apt-get update && apt-get install -y \
    git \
    ansible \
 && rm -rf /var/lib/apt/lists/*

RUN echo "[local]\nlocalhost ansible_connection=local\n[defaults]\nroles_path=/home/roles\n" > /home/tests/ansible.cfg

ENTRYPOINT ["/sbin/init"]
